sudo: required 

language: generic 

services:
  - docker 

before_install:
  - docker build -t artur5236/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true artur5236/docker-react npm run test
